# Generated by Django 2.0.4 on 2018-05-05 10:36

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPdfPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=main.models.get_pdf_file_path)),
            ],
        ),
    ]
