# Generated by Django 2.0.4 on 2018-05-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180501_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
