# Generated by Django 2.0.4 on 2018-05-05 06:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_line',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
