# Generated by Django 2.0.4 on 2018-05-02 17:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_quotation_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_payed',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(default='01', max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unique_code',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
