# Generated by Django 2.0.4 on 2018-05-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
