# Generated by Django 2.0.4 on 2018-05-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180505_0104'),
        ('inventory', '0004_auto_20180505_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscale',
            name='distribution_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DistributionChannel'),
        ),
    ]
